### ISSUE TITLE
Matt's Project

### ISSUE THREAD

**Issue by duffin22** [ga-students/project02#2]
https://github.com/duffin22/cocktail-app-2

**Comment by BradZzz** [comment]
Matt

Great Job! Your app was pretty damn near perfect from the UI side of things. As a rule of thumb, I like to give criticisms no matter how small, so here they are.

No Readme: You need a readme when you put this into your portfolio so that potential employers can see right away what you are doing. Makes things look professional.

Comments in code: Comments that aren’t used to explain sections of code need to be taken out before the code is pushed to production.

Cocktail-app-2.java: This file could have been done a much better way. Maybe adding some of those strings you created to a new table in your database could have made things easier for you in the long run. Also would have cut down on how long that source file was.

Again, great job! A professional, bug free, project 2 application. Keep up the amazing work!

Allow the user to view data from database - 3
Data is shown in a meaningful way - 3
Incorporates Material Design - 3
Incorporate Object Oriented principles into your app - 3

Uses an api - no
Uses JUnit Testing - no
Uses Espresso Testing - no
Can search in database - yes
Can insert/delete in database - no 

Total: 13
